[package]
name = "r8080"
version = "0.1.0"
authors = ["Mauricio Vera <veramauricio92@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
